version: '3'
services:
   api:
     build: .
     command: ["pytest", "-vv", "--cov=docker_builder"] 
     ports: 
     - 8080:8080
     environment: 
      REDIS_URL: redis://redis:6379
     depends_on:
     - redis
     - worker
     volumes:
      - .:/docker-builder/
     working_dir: /root/docker-builder/
   redis:
     image: "redis:alpine"
     ports: 
     - "6739:6739"
     expose: 
     - "6739"
     volumes:
      - redis_data:/data
   worker:
    build: .
    command: python worker.py
    environment: 
      REDIS_URL: redis://redis:6379
    depends_on:
     - redis
volumes:  
  redis_data:


