version: 2

jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - run: 
         working_directory: ~/project/
         command: docker-compose -f docker-compose-test.yaml run api
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-test