version: 2

jobs:
  build-and-test:
    machine:
      image: cimg/base:2020.01
    steps:
      - checkout
      - run: |
          sudo apt install docker.io
          sudo apt install docker-compose
      - run: docker-compose -f docker-compose-test.yaml run api
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-test