version: 2

jobs:
  build-and-test:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - setup_remote_docker
      - run: 
         working_directory: ~/project/docker-builder
         command: docker-compose -f docker-compose-test.yaml run api
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-test